export const CHANGE_CATEGORY = "CHANGE_CATEGORY";
export const CHANGE_DIFFICULTY = "CHANGE_DIFFICULTY";
export const CHANGE_LIMIT = "CHANGE_LIMIT";
export const CHANGE_NAME = "CHANGE_NAME";
export const CHANGE_SCORE = "CHANGE_SCORE";
export const QUESTION_ANSWERS="QUSETION_ANSWERS"
export const USER_ANSWERS="USER_ANSWERS"
